# Generated by Django 3.2.6 on 2022-01-21 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminUser', '0002_auto_20220120_1246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newpostbyadmin',
            name='category',
        ),
        migrations.DeleteModel(
            name='NewCategoryPostByAdmin',
        ),
        migrations.DeleteModel(
            name='NewPostByAdmin',
        ),
    ]
