# Generated by Django 3.2.6 on 2021-09-26 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('duration', models.IntegerField()),
                ('related_field', models.CharField(choices=[('Medical', 'Medical'), ('Enginnering', 'Enginnering')], max_length=100)),
                ('created', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Examination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('level_of_exam', models.CharField(choices=[('State', 'State'), ('National', 'National'), ('Institute', 'Institute')], max_length=50, null=True)),
                ('related_exam', models.CharField(choices=[('Medical', 'Medical'), ('Enginnering', 'Enginnering')], max_length=100)),
                ('created', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalCollege',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('sortname', models.CharField(max_length=50, null=True)),
                ('approved', models.CharField(max_length=200)),
                ('level', models.CharField(max_length=50)),
                ('state_ranking', models.IntegerField()),
                ('national_ranking', models.IntegerField()),
                ('branch', models.IntegerField()),
                ('sit', models.IntegerField()),
                ('establishment', models.DateField()),
                ('staff', models.IntegerField(null=True)),
                ('autonomus', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=5)),
                ('university', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='college/image')),
                ('about_college', models.TextField()),
                ('properties', models.CharField(choices=[('Privete', 'Private'), ('Government', 'Government'), ('Semi-Government', 'Semi-Government')], max_length=30, null=True)),
                ('last_year_rank', models.IntegerField(null=True)),
                ('cutoff', models.IntegerField(null=True)),
                ('annual_free', models.IntegerField(null=True)),
                ('city', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=50)),
                ('landmark', models.CharField(max_length=100)),
                ('postal_address', models.CharField(max_length=200)),
                ('pincode', models.IntegerField()),
                ('available_course', models.ManyToManyField(related_name='course', to='college.Course')),
                ('entrance_exam', models.ManyToManyField(related_name='entrance', to='college.Examination')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='entrance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='college.examination'),
        ),
    ]
