# Generated by Django 3.2.6 on 2021-09-26 14:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='banner/image')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_title', models.CharField(max_length=200)),
                ('status', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('com_title', models.CharField(blank=True, max_length=500, null=True)),
                ('com_image', models.ImageField(blank=True, null=True, upload_to='com/')),
                ('chief_complaint', models.TextField(blank=True, null=True)),
                ('present_illness', models.TextField(blank=True, null=True)),
                ('past_illness', models.TextField(blank=True, null=True)),
                ('drugs', models.CharField(blank=True, max_length=500, null=True)),
                ('personal', models.TextField(blank=True, null=True)),
                ('family', models.CharField(blank=True, max_length=500, null=True)),
                ('physical_exam', models.TextField(blank=True, null=True)),
                ('system_exam', models.CharField(blank=True, max_length=500, null=True)),
                ('local_exam', models.CharField(blank=True, max_length=200, null=True)),
                ('vitus', models.CharField(blank=True, max_length=200, null=True)),
                ('lab_finding', models.CharField(blank=True, max_length=200, null=True)),
                ('imaging', models.CharField(blank=True, max_length=200, null=True)),
                ('diagnosis', models.CharField(blank=True, max_length=500, null=True)),
                ('complaint_status', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now=True, null=True)),
                ('update', models.DateTimeField(auto_now_add=True, null=True)),
                ('bookmark', models.ManyToManyField(blank=True, default=None, related_name='case_bookmark', to=settings.AUTH_USER_MODEL)),
                ('complaint_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(related_name='case_likes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Custome_Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=200)),
                ('job_position', models.CharField(max_length=100)),
                ('type_of_hospital', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=100)),
                ('minimum_salary', models.IntegerField()),
                ('work_expericence', models.CharField(max_length=100)),
                ('jobType', models.CharField(max_length=200)),
                ('allowance', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='HomeBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='banner/home/image')),
            ],
        ),
        migrations.CreateModel(
            name='Identification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20, null=True)),
                ('status', models.BooleanField(default=False)),
                ('userdetail', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('phone_number',)},
            },
        ),
        migrations.CreateModel(
            name='Job_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobtype', models.CharField(choices=[('Part Time', 'Part_Time'), ('Full_Time', 'Full_Time')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poll_title', models.CharField(max_length=500, null=True)),
                ('poll_image', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='news/image/')),
                ('option1', models.CharField(max_length=200, null=True)),
                ('option2', models.CharField(max_length=200, null=True)),
                ('option3', models.CharField(max_length=200, null=True)),
                ('option4', models.CharField(max_length=200, null=True)),
                ('poll_status', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('update', models.DateTimeField(auto_now_add=True, null=True)),
                ('bookmark', models.ManyToManyField(blank=True, default=None, related_name='pollbookmark', to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(related_name='poll_likes', to=settings.AUTH_USER_MODEL)),
                ('poll_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RequestJobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orginization_name', models.CharField(max_length=200)),
                ('hospital_type', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('contact', models.CharField(max_length=20)),
                ('department', models.CharField(max_length=1000, null=True)),
                ('position', models.CharField(max_length=1000, null=True)),
                ('salay', models.CharField(max_length=1000, null=True)),
                ('vacancy', models.IntegerField(null=True)),
                ('jobtype', models.CharField(choices=[('Part Time', 'Part_Time'), ('Full_Time', 'Full_Time')], max_length=100, null=True)),
                ('status', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now=True)),
                ('update', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Validate_Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20, null=True)),
                ('OTP', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='subject')),
                ('name', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'unique_together': {('name',)},
            },
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_salary', models.IntegerField()),
            ],
            options={
                'unique_together': {('min_salary',)},
            },
        ),
        migrations.CreateModel(
            name='ResumeUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_file', models.FileField(upload_to='resume')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_name', models.CharField(max_length=50, null=True)),
                ('profileImage', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='profile/image')),
                ('status', models.BooleanField(default=False, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('contact', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='job.identification')),
                ('follow', models.ManyToManyField(related_name='follow', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('contact',)},
            },
        ),
        migrations.CreateModel(
            name='PollVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=5)),
                ('vote', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('poll_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.poll')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PollComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('poll_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.poll')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NewsArticalPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artical_title', models.CharField(max_length=200, null=True)),
                ('artical_image', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='news/image/')),
                ('artical_discription', models.TextField()),
                ('artical_status', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now_add=True, null=True)),
                ('bookmark', models.ManyToManyField(blank=True, default=None, related_name='newsartical', to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(related_name='artical_likes', to=settings.AUTH_USER_MODEL)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NewsArtical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=200, null=True)),
                ('sub_headline', models.CharField(max_length=200, null=True)),
                ('title', models.CharField(max_length=2000, null=True, verbose_name='News Title')),
                ('image', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='news/image/')),
                ('discription', models.TextField()),
                ('byother', models.BooleanField(default=False)),
                ('author', models.CharField(max_length=200, null=True)),
                ('update', models.DateTimeField()),
                ('visiable', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.category')),
            ],
        ),
        migrations.CreateModel(
            name='MultiImageStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='multi_image/status/image')),
                ('created', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='job.profile')),
            ],
        ),
        migrations.CreateModel(
            name='MultiImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='multi_image/image/')),
                ('complaint_status', models.BooleanField(default=False)),
                ('newspoll_status', models.BooleanField(default=False)),
                ('complaint', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compaint', to='job.complaint')),
                ('news_poll', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='poll', to='job.poll')),
            ],
        ),
        migrations.CreateModel(
            name='Job_By_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='job_title')),
                ('dep', models.BooleanField(default=False)),
                ('loc', models.BooleanField(default=False)),
                ('both', models.BooleanField(default=False)),
            ],
            options={
                'unique_together': {('title',)},
            },
        ),
        migrations.CreateModel(
            name='Hospital_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospitaltype', models.CharField(max_length=200)),
            ],
            options={
                'unique_together': {('hospitaltype',)},
            },
        ),
        migrations.CreateModel(
            name='Hospital_Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=200)),
            ],
            options={
                'unique_together': {('department_name',)},
            },
        ),
        migrations.CreateModel(
            name='Experince',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_experince', models.CharField(max_length=20, null=True)),
            ],
            options={
                'unique_together': {('min_experince',)},
            },
        ),
        migrations.CreateModel(
            name='Discussions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('case_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.complaint')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=200)),
            ],
            options={
                'unique_together': {('position',)},
            },
        ),
        migrations.CreateModel(
            name='College_Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_story', models.CharField(max_length=200)),
                ('college_name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('photos', imagekit.models.fields.ProcessedImageField(upload_to='news/image/')),
                ('event_discription', models.TextField()),
                ('story_date', models.DateTimeField(auto_now=True, null=True)),
                ('college_story_status', models.BooleanField(default=False)),
                ('update', models.DateTimeField(auto_now_add=True, null=True)),
                ('bookmark', models.ManyToManyField(blank=True, default=None, related_name='college_story_bookmark', to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(related_name='college_story_likes', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_city_name', models.CharField(max_length=100)),
            ],
            options={
                'unique_together': {('hospital_city_name',)},
            },
        ),
        migrations.CreateModel(
            name='Category_Related_Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(db_column='Consultent department', max_length=500, verbose_name='consultent department')),
                ('sub_heading', models.CharField(db_column='consultent position', max_length=500, verbose_name='consultent position')),
                ('company_name', models.CharField(blank=True, max_length=500, null=True, verbose_name='company/Hospital name')),
                ('sector', models.CharField(choices=[('Private', 'PRIVATE'), ('Govrnment', 'GOVRNMENT'), ('Semi_Govt', 'SEMI_GOVT'), ('Startup', 'STARTUP')], max_length=100, null=True)),
                ('image', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='Hospital image')),
                ('location', models.CharField(db_column='Hospital Location', max_length=100, verbose_name='Hospital Location')),
                ('salary', models.IntegerField()),
                ('monthly_or_anual', models.CharField(choices=[('Monthly', 'MONTHLY'), ('Anual', 'ANUAL')], default='Monthly', max_length=100)),
                ('experince', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('job_status', models.BooleanField(default=True)),
                ('gender', models.CharField(choices=[('Female', 'FEMALE'), ('Male', 'MALE'), ('Male/Female', 'MALE/FEMALE')], default='Male', max_length=20, verbose_name=' Gender preference')),
                ('qualification', models.CharField(max_length=500)),
                ('designation', models.CharField(max_length=100, null=True)),
                ('vacancy', models.IntegerField()),
                ('working_hours', models.CharField(max_length=100)),
                ('working_day', models.CharField(max_length=100)),
                ('shift', models.CharField(choices=[('Day_Shift', 'DAY_SHIFT'), ('Night_Shift', 'NIGTH_SHIFT'), ('Remotly', 'REMOTLY')], default='Remotly', max_length=20)),
                ('discription', models.TextField(verbose_name='job discription')),
                ('aboutus', models.TextField()),
                ('role', models.CharField(max_length=200, verbose_name='Consultant Role')),
                ('course', models.CharField(blank=True, max_length=100, null=True, verbose_name='Qualification')),
                ('accommodation', models.CharField(max_length=20)),
                ('skills', models.CharField(max_length=500)),
                ('hospital_type', models.CharField(max_length=100, null=True)),
                ('job_type', models.CharField(choices=[('Part_Time', 'Part_Time'), ('Full_Time', 'Full_Time')], max_length=100, null=True)),
                ('total_bed', models.IntegerField(null=True)),
                ('icu', models.IntegerField(null=True)),
                ('nicuc', models.IntegerField(null=True)),
                ('picu', models.IntegerField(null=True)),
                ('department', models.CharField(blank=True, max_length=500, null=True)),
                ('top_job', models.BooleanField(default=False)),
                ('post_date', models.DateField(null=True)),
                ('applicant', models.ManyToManyField(related_name='application', to=settings.AUTH_USER_MODEL)),
                ('bookmark', models.ManyToManyField(related_name='bookmarks', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.job_by_category')),
                ('likes', models.ManyToManyField(related_name='like', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Articals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artical_title', models.CharField(max_length=200)),
                ('mediafile', imagekit.models.fields.ProcessedImageField(null=True, upload_to='news/image/')),
                ('artical_discription', models.TextField()),
                ('art_status', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now=True, null=True)),
                ('update', models.DateTimeField(auto_now_add=True, null=True)),
                ('bookmark', models.ManyToManyField(related_name='articalsbookmark', to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(related_name='articalslike', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ArticalComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('artical_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.articals')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Accommodation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accommodation', models.CharField(max_length=100)),
            ],
            options={
                'unique_together': {('accommodation',)},
            },
        ),
    ]
