# Generated by Django 3.2.6 on 2021-09-27 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category_related_job',
            name='delete_job',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='category_related_job',
            name='hide_job',
            field=models.BooleanField(default=False),
        ),
    ]
