# Generated by Django 3.2.6 on 2021-09-27 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_auto_20210927_1213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category_related_job',
            name='hide_job',
        ),
    ]
