# Generated by Django 3.2.6 on 2021-09-28 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_remove_category_related_job_hide_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='category_related_job',
            name='resion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
