# Generated by Django 3.2.6 on 2021-09-28 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_category_related_job_resion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category_related_job',
            name='resion',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
