# Generated by Django 3.2.6 on 2021-09-28 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_alter_category_related_job_resion'),
    ]

    operations = [
        migrations.AddField(
            model_name='category_related_job',
            name='hide_resion',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='category_related_job',
            name='resion',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
