# Generated by Django 3.2.6 on 2021-09-28 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_auto_20210928_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticalpost',
            name='artical_image',
            field=models.ImageField(blank=True, null=True, upload_to='news/image/'),
        ),
    ]
