# Generated by Django 3.2.6 on 2021-09-28 19:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('job', '0007_alter_newsarticalpost_artical_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='custome_job',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='articals',
            name='mediafile',
            field=models.ImageField(null=True, upload_to='news/image/'),
        ),
        migrations.AlterField(
            model_name='college_story',
            name='photos',
            field=models.ImageField(null=True, upload_to='news/image/'),
        ),
        migrations.AlterField(
            model_name='job_by_category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='job_title'),
        ),
        migrations.AlterField(
            model_name='multiimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='multi_image/image/'),
        ),
        migrations.AlterField(
            model_name='multiimagestatus',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='multi_image/status/image'),
        ),
        migrations.AlterField(
            model_name='newsartical',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='news/image/'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='poll_image',
            field=models.ImageField(blank=True, null=True, upload_to='news/image/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profileImage',
            field=models.ImageField(blank=True, null=True, upload_to='profile/image'),
        ),
    ]
