# Generated by Django 3.2.6 on 2021-10-01 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0009_auto_20210930_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='identification',
            name='dob',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='identification',
            name='gender',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='identification',
            name='language',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='identification',
            name='location',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
