# Generated by Django 3.2.6 on 2021-10-04 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0015_profile_tell_me_about_youself'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='job_location',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
