# Generated by Django 3.2.6 on 2021-10-04 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0016_profile_job_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='job_location',
            new_name='current_job_location',
        ),
    ]
