# Generated by Django 3.2.6 on 2021-10-06 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0017_rename_job_location_profile_current_job_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='present_date',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='resumeupload',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
