# Generated by Django 3.2.6 on 2021-10-06 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0018_auto_20211006_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='end_date',
            field=models.DateField(blank=True),
        ),
    ]
