# Generated by Django 3.2.6 on 2021-10-06 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0020_alter_experience_end_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='present_date',
        ),
        migrations.AlterField(
            model_name='experience',
            name='end_date',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
