# Generated by Django 3.2.6 on 2021-10-07 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0023_profile_skill'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Skills',
        ),
    ]
