# Generated by Django 3.2.6 on 2021-10-09 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0024_delete_skills'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Validate_Phone',
        ),
    ]
