# Generated by Django 3.2.6 on 2021-10-22 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0025_delete_validate_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='category_related_job',
            name='hr_contact',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
