# Generated by Django 3.2.6 on 2021-10-22 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0026_category_related_job_hr_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category_related_job',
            name='hr_contact',
            field=models.CharField(default='1234567890', max_length=20, null=True),
        ),
    ]
