# Generated by Django 3.2.6 on 2021-10-22 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0027_alter_category_related_job_hr_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='category_related_job',
            name='social_contact',
            field=models.CharField(default='0123456789', max_length=20, null=True),
        ),
    ]
