# Generated by Django 3.2.6 on 2021-12-13 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0031_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaveOtp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('otp', models.CharField(max_length=5)),
            ],
        ),
    ]
