# Generated by Django 3.2.6 on 2021-12-23 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0032_saveotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_by_category',
            name='category_status',
            field=models.BooleanField(default=True),
        ),
    ]
