# Generated by Django 3.2.6 on 2022-01-04 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0034_auto_20220104_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='identification',
            name='profile_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
