# Generated by Django 3.2.6 on 2022-01-06 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0035_identification_profile_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articals',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='articals',
            name='update',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='identification',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
