# Generated by Django 3.2.6 on 2022-01-12 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0036_auto_20220106_2056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job_by_category',
            name='both',
        ),
        migrations.RemoveField(
            model_name='job_by_category',
            name='dep',
        ),
        migrations.RemoveField(
            model_name='job_by_category',
            name='loc',
        ),
        migrations.AddField(
            model_name='job_by_category',
            name='abount',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
