# Generated by Django 3.2.6 on 2022-01-12 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0037_auto_20220112_1313'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job_by_category',
            old_name='abount',
            new_name='about',
        ),
    ]
