# Generated by Django 3.2.6 on 2022-01-13 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0039_auto_20220113_1212'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category_related_job',
            old_name='image',
            new_name='hospitail_image',
        ),
        migrations.RemoveField(
            model_name='category_related_job',
            name='aboutus',
        ),
        migrations.RemoveField(
            model_name='category_related_job',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='category_related_job',
            name='course',
        ),
        migrations.RemoveField(
            model_name='category_related_job',
            name='delete_job',
        ),
        migrations.RemoveField(
            model_name='category_related_job',
            name='department',
        ),
        migrations.RemoveField(
            model_name='category_related_job',
            name='headline',
        ),
        migrations.RemoveField(
            model_name='category_related_job',
            name='hide_resion',
        ),
        migrations.RemoveField(
            model_name='category_related_job',
            name='role',
        ),
        migrations.RemoveField(
            model_name='category_related_job',
            name='sector',
        ),
        migrations.RemoveField(
            model_name='category_related_job',
            name='shift',
        ),
        migrations.RemoveField(
            model_name='category_related_job',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='category_related_job',
            name='sub_heading',
        ),
        migrations.AddField(
            model_name='category_related_job',
            name='Speciality',
            field=models.CharField(db_column='Consultent speciality', max_length=500, null=True, verbose_name='consultent department'),
        ),
        migrations.AddField(
            model_name='category_related_job',
            name='hosptial_name',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Hospital name'),
        ),
        migrations.AlterField(
            model_name='category_related_job',
            name='designation',
            field=models.CharField(db_column='consultent Designation', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='category_related_job',
            name='discription',
            field=models.TextField(db_column='Role And Responsibility'),
        ),
        migrations.AlterField(
            model_name='category_related_job',
            name='experince',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='category_related_job',
            name='location',
            field=models.CharField(db_column='Job Location', max_length=100, null=True, verbose_name='Hospital Location'),
        ),
        migrations.AlterField(
            model_name='category_related_job',
            name='monthly_or_anual',
            field=models.CharField(choices=[('Monthly', 'MONTHLY'), ('Anual', 'ANNUAL')], default='Monthly', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='category_related_job',
            name='salary',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='salary',
            name='min_salary',
            field=models.FloatField(),
        ),
    ]
