# Generated by Django 3.2.6 on 2022-01-14 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0040_auto_20220113_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='category_related_job',
            name='state',
            field=models.CharField(max_length=200, null=True, verbose_name='Job State'),
        ),
        migrations.AlterField(
            model_name='category_related_job',
            name='Speciality',
            field=models.CharField(max_length=500, null=True, verbose_name='consultent speciality'),
        ),
        migrations.AlterField(
            model_name='category_related_job',
            name='discription',
            field=models.TextField(verbose_name='Role And Responsibility'),
        ),
        migrations.AlterField(
            model_name='category_related_job',
            name='location',
            field=models.CharField(max_length=100, null=True, verbose_name='Job Location'),
        ),
        migrations.AlterField(
            model_name='category_related_job',
            name='monthly_or_anual',
            field=models.CharField(choices=[('Monthly', 'MONTHLY'), ('Anual', 'ANNUAL')], default='Monthly', max_length=100, null=True, verbose_name='Monthly/Annual'),
        ),
        migrations.AlterField(
            model_name='category_related_job',
            name='working_day',
            field=models.CharField(max_length=100, verbose_name='Woking Day'),
        ),
        migrations.AlterField(
            model_name='category_related_job',
            name='working_hours',
            field=models.CharField(max_length=100, verbose_name='Working Hours'),
        ),
    ]
