# Generated by Django 3.2.6 on 2022-01-20 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0041_auto_20220114_1140'),
    ]

    operations = [
        migrations.CreateModel(
            name='HigherQualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification', models.CharField(max_length=200, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Doctor_Specialist',
        ),
        migrations.DeleteModel(
            name='Doctor_Super_Specialist',
        ),
        migrations.DeleteModel(
            name='Graduation',
        ),
        migrations.RemoveField(
            model_name='location',
            name='state',
        ),
        migrations.DeleteModel(
            name='Position',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
