# Generated by Django 3.2.6 on 2022-01-21 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0042_auto_20220120_1107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='identification',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='identification',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='identification',
            name='language',
        ),
        migrations.RemoveField(
            model_name='identification',
            name='location',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='profile_name',
        ),
        migrations.AddField(
            model_name='profile',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='language',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
