# Generated by Django 3.2.6 on 2022-01-21 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0043_auto_20220121_1112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='current_job_location',
        ),
    ]
