# Generated by Django 3.2.6 on 2022-01-24 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0044_remove_profile_current_job_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category_related_job',
            name='experince',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='category_related_job',
            name='salary',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
