# Generated by Django 3.2.6 on 2022-01-25 09:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('job', '0045_auto_20220124_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollcomment',
            name='opinion',
            field=models.ManyToManyField(related_name='agree_and_disagree', to=settings.AUTH_USER_MODEL),
        ),
    ]
