# Generated by Django 3.2.6 on 2022-01-25 10:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('job', '0047_discussions_opinion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discussions',
            name='opinion',
        ),
        migrations.RemoveField(
            model_name='pollcomment',
            name='opinion',
        ),
        migrations.AddField(
            model_name='discussions',
            name='agree',
            field=models.ManyToManyField(related_name='case_agree', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='discussions',
            name='disagree',
            field=models.ManyToManyField(related_name='case_disagree', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pollcomment',
            name='agree',
            field=models.ManyToManyField(related_name='poll_agree', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pollcomment',
            name='disagree',
            field=models.ManyToManyField(related_name='Poll_disagree', to=settings.AUTH_USER_MODEL),
        ),
    ]
