# Generated by Django 3.2.6 on 2022-01-29 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0049_recentsearch'),
    ]

    operations = [
        migrations.AddField(
            model_name='recentsearch',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
