# Generated by Django 3.2.6 on 2022-01-29 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0051_recentsearch_update'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recentsearch',
            name='update',
        ),
    ]
