# Generated by Django 3.2.6 on 2022-03-25 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0052_remove_recentsearch_update'),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='hostpital/image')),
            ],
        ),
        migrations.DeleteModel(
            name='Banner',
        ),
        migrations.RemoveField(
            model_name='custome_job',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='HomeBanner',
        ),
        migrations.DeleteModel(
            name='Job_Type',
        ),
        migrations.RemoveField(
            model_name='multiimage',
            name='complaint',
        ),
        migrations.RemoveField(
            model_name='multiimage',
            name='news_poll',
        ),
        migrations.RemoveField(
            model_name='multiimagestatus',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='newsartical',
            name='news',
        ),
        migrations.RemoveField(
            model_name='recentsearch',
            name='user',
        ),
        migrations.DeleteModel(
            name='RequestJobPost',
        ),
        migrations.AlterField(
            model_name='category_related_job',
            name='job_type',
            field=models.CharField(choices=[('Part Time', 'Part Time'), ('Full Time', 'Full Time')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='complaint_status',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Custome_Job',
        ),
        migrations.DeleteModel(
            name='MultiImage',
        ),
        migrations.DeleteModel(
            name='MultiImageStatus',
        ),
        migrations.DeleteModel(
            name='NewsArtical',
        ),
        migrations.DeleteModel(
            name='RecentSearch',
        ),
        migrations.AddField(
            model_name='hospitalbanner',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='job.category_related_job'),
        ),
    ]
