# Generated by Django 3.2.6 on 2022-04-03 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0053_auto_20220325_1010'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(null=True, upload_to='banner/image')),
            ],
        ),
        migrations.CreateModel(
            name='HospitalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('typeofhospital', models.CharField(max_length=200, null=True)),
                ('city', models.CharField(max_length=200, null=True)),
                ('location', models.CharField(max_length=200, null=True)),
                ('state', models.CharField(max_length=200, null=True)),
                ('no_of_OT', models.CharField(max_length=200, null=True)),
                ('no_of_sepeciality', models.CharField(max_length=200)),
                ('no_of_bed', models.CharField(max_length=200)),
                ('daily_OPD', models.CharField(max_length=200)),
                ('icu', models.IntegerField(null=True)),
                ('nicuc', models.IntegerField(null=True)),
                ('picu', models.IntegerField(null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='articalcomment',
            old_name='artical_id',
            new_name='artical',
        ),
        migrations.RenameField(
            model_name='articals',
            old_name='artical_discription',
            new_name='discription',
        ),
        migrations.RenameField(
            model_name='articals',
            old_name='mediafile',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='articals',
            old_name='art_status',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='articals',
            old_name='artical_title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='college_story',
            old_name='event_discription',
            new_name='discription',
        ),
        migrations.RenameField(
            model_name='college_story',
            old_name='college_story_status',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='college_story',
            old_name='story_date',
            new_name='storydate',
        ),
        migrations.RenameField(
            model_name='complaint',
            old_name='complaint_id',
            new_name='complaint',
        ),
        migrations.RenameField(
            model_name='complaint',
            old_name='com_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='complaint',
            old_name='com_title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='discussions',
            old_name='case_id',
            new_name='case',
        ),
        migrations.RenameField(
            model_name='newsarticalpost',
            old_name='artical_discription',
            new_name='discription',
        ),
        migrations.RenameField(
            model_name='newsarticalpost',
            old_name='artical_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='newsarticalpost',
            old_name='artical_status',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='newsarticalpost',
            old_name='artical_title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='poll',
            old_name='poll_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='poll',
            old_name='poll_title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='pollcomment',
            old_name='poll_id',
            new_name='poll',
        ),
        migrations.RenameField(
            model_name='pollvote',
            old_name='poll_id',
            new_name='poll',
        ),
        migrations.RemoveField(
            model_name='category_related_job',
            name='hospitail_image',
        ),
        migrations.RemoveField(
            model_name='category_related_job',
            name='icu',
        ),
        migrations.RemoveField(
            model_name='category_related_job',
            name='nicuc',
        ),
        migrations.RemoveField(
            model_name='category_related_job',
            name='picu',
        ),
        migrations.RemoveField(
            model_name='category_related_job',
            name='state',
        ),
        migrations.RemoveField(
            model_name='category_related_job',
            name='top_job',
        ),
        migrations.RemoveField(
            model_name='category_related_job',
            name='total_bed',
        ),
        migrations.RemoveField(
            model_name='hospitalbanner',
            name='image',
        ),
        migrations.RemoveField(
            model_name='hospitalbanner',
            name='job',
        ),
        migrations.AddField(
            model_name='hospitalbanner',
            name='file',
            field=models.FileField(null=True, upload_to='hostpital/image'),
        ),
        migrations.CreateModel(
            name='HospitalSpeciality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(null=True, upload_to='hostpital/image')),
                ('hospital', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='job.hospitalinfo')),
            ],
        ),
        migrations.CreateModel(
            name='HospitalHighlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(null=True, upload_to='hostpital/image')),
                ('hospital', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='job.hospitalinfo')),
            ],
        ),
        migrations.AddField(
            model_name='hospitalbanner',
            name='hospital',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='job.hospitalinfo'),
        ),
    ]
